### ISSUE TITLE
result of Monodepth2?

### ISSUE THREAD

**Issue by SBaokun** [JohnsonLC/MotionHint#1]
MonoDepth2 (Baseline) 14.837 3.299 68.180 12.097 4.949 19.408
                                      15.079 3.335 69.019 12.102  4.927 19.371
Thank you very much for your work.
But I found the results of (MonoDepth2). in the paper is different from that in the code. May I ask why is this?

**Comment by conallwang** [comment]
Hi SBaokun,

Sorry for the late response.

I don't make it clear in the paper. The reported results of MonoDepth2 in the paper are obtained by fine-tuning the original version for ~80 epochs, while the results in the code are fine-tuned for only 20 epochs. 

Cong

**Comment by SBaokun** [comment]
thank  you !!
