### ISSUE TITLE
Questions about the 09 trajectory in the article

### ISSUE THREAD

**Issue by jzwqaq** [JohnsonLC/MotionHint#3]
hello, thanks for your shared code. Its a great work！
I try to use the weights provided at the end of your homepage to evaluate the 09 and 10 sequence, I can get the same trajectory error and other data, but I can't get a trajectory that is close to a closed track like Figure 1 in your article, I want to know Figure 1 in your article Which weights are used to obtain such a result. Because I used the MotionHint-GT and MotionHint-Unpair weights at the end of your homepage, I can't get the same effect as your picture in evo toolbox.

Wish you can  apply me  soon, thx a lot.

**Comment by conallwang** [comment]
Hi jzw,

Thanks for your interest in our work.

As stated in our abstract, we actually take two existing SSM-VO systems (Monodepth2 and SC-Depth) as our baseline and perform evaluations. In this repo, we only publish the code and pre-trained models of Monodepth2, not SC-Depth. Fig. 1 in the original paper shows the results of SC-Depth and our improved versions.

Cong
